# Generated by Django 4.2.1 on 2023-05-04 16:36

import django.contrib.auth.password_validation
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_password_validators.password_character_requirements.password_validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20, validators=[django.contrib.auth.password_validation.MinimumLengthValidator, django_password_validators.password_character_requirements.password_validation.PasswordCharacterValidator])),
                ('account_name', models.CharField(max_length=150)),
                ('acc_secret', models.UUIDField(default='0c9382c72a694c02ad2dd6ad1eebab4d', editable=False, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('http_method', models.CharField(max_length=20)),
                ('headers', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc_dest.accounts')),
            ],
        ),
    ]
