# Generated by Django 4.2.1 on 2023-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_dest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acc_secret',
            field=models.UUIDField(default='23c5f7a737834fe7a6a4e98f3bf5ba9b', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
