# Generated by Django 4.2.1 on 2023-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_dest', '0002_alter_accounts_acc_secret_alter_accounts_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='acc_secret',
            field=models.UUIDField(default='570ef5a0a72b4eef9af25a64aa1f86aa', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='http_method',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET')], max_length=20),
        ),
    ]
